In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

In [5]:
base = pd.read_csv("iris.csv")

In [20]:
labelencoder = LabelEncoder()

# RESOLVENDO ṔRIMEIRO PROBLEMA
# Transforma de string para valor numerico (0 , 1 , 2)
classe = labelencoder.fit_transform(classe) 

# RESOLVENDO SEGUNDO PROBLEMA 
#Porém ele transforma em valor unidmensional, e ele precisa ter três, logo necessita mais uma ação
# Transforma em variavel dummy conforme abaixo, e em um valor tri diomensional, conforme dummy permite fazer
# Transforma categorico com combinações para problemas categoricos com mais de duas labels possiveis
classe_dummy  = np_utils.to_categorical(classe) 
# iris setosa    1 0 0 
# iris virginica 0 1 0
# iris versicolo 0 0 1

In [27]:
previsores_train, previsores_test, classe_train, classe_test = train_test_split(previsores, classe_dummy, test_size=0.25)

In [28]:
classificador = Sequential()

# Usar aquela formula para definir número de camadas ocultas 
# (entradas + saida) / 2, nesse caso (4+3)/2 = 3.5, arrendonda 4
#Deixa a inicializaão dos pesos padrão.
classificador.add(Dense(units =4, activation = 'relu', input_dim = 4)) 
classificador.add(Dense(units =4, activation = 'relu'))
classificador.add(Dense(units=3, activation = 'softmax'))

classificador.compile(optimizer = 'adam', loss= 'categorical_crossentropy',
                         metrics=['categorical_accuracy'])

In [29]:
#Não vai funcionar o código abaixo, e necessario algumas modificações, ele espera um shape(3,) mas tem como retorno (1,) 
# classificador.fit(previsores_train, classe_train, batch_size = 10,epochs = 100)


# DUas coisas que precisamos fazer, os labels estão em string(formato categorico), e necessario trasformção para formato númerico
    # Usar LabelEncoder

# COmo ele precisa ter trimensões, a configuração correta tem que ficar: 
    # Usar np_utils
        # iris setosa     1 0 0
        # iris virginica  0 1 0
        # iris versicolor 0 0 1 
        
#Após esses ajustes pode-se usar o código substituindo o 'classe' por 'classe_dummy' na parte do 'train_test_split'
    # classificador.fit(previsores_train, classe_train, batch_size = 10,epochs = 100)

In [31]:
classificador.fit(previsores_train, classe_train, batch_size = 10,epochs = 100)

# Esse valor de precisão se refere ao teste na própria base de treinamento e fazendo a avaliação nela mesmo
# Logo não é um resultado real pra afirmar se o algoritimo está de fato tendo bons resultados
# deve-se fazer isso com os dados de teste

Epoch 1/100
112/112 [==============================] - 0s 753us/step - loss: 0.1942 - categorical_accuracy: 0.9643
Epoch 2/100
112/112 [==============================] - 0s 507us/step - loss: 0.1967 - categorical_accuracy: 0.9643
Epoch 3/100
112/112 [==============================] - 0s 467us/step - loss: 0.1932 - categorical_accuracy: 0.9643
Epoch 4/100
112/112 [==============================] - 0s 277us/step - loss: 0.1889 - categorical_accuracy: 0.9643
Epoch 5/100
112/112 [==============================] - 0s 240us/step - loss: 0.1882 - categorical_accuracy: 0.9643
Epoch 6/100
112/112 [==============================] - 0s 194us/step - loss: 0.1845 - categorical_accuracy: 0.9643
Epoch 7/100
112/112 [==============================] - 0s 219us/step - loss: 0.1835 - categorical_accuracy: 0.9643
Epoch 8/100
112/112 [==============================] - 0s 219us/step - loss: 0.1808 - categorical_accuracy: 0.9643
Epoch 9/100
112/112 [==============================] - 0s 119us/step - loss: 0.1

112/112 [==============================] - 0s 232us/step - loss: 0.1043 - categorical_accuracy: 0.9643
Epoch 72/100
112/112 [==============================] - 0s 127us/step - loss: 0.1076 - categorical_accuracy: 0.9643
Epoch 73/100
112/112 [==============================] - 0s 227us/step - loss: 0.1042 - categorical_accuracy: 0.9643
Epoch 74/100
112/112 [==============================] - 0s 178us/step - loss: 0.1043 - categorical_accuracy: 0.9643
Epoch 75/100
112/112 [==============================] - 0s 156us/step - loss: 0.1017 - categorical_accuracy: 0.9643
Epoch 76/100
112/112 [==============================] - 0s 150us/step - loss: 0.1018 - categorical_accuracy: 0.9643
Epoch 77/100
112/112 [==============================] - 0s 170us/step - loss: 0.1009 - categorical_accuracy: 0.9643
Epoch 78/100
112/112 [==============================] - 0s 196us/step - loss: 0.1015 - categorical_accuracy: 0.9643
Epoch 79/100
112/112 [==============================] - 0s 148us/step - loss: 0.1025 

In [33]:
resultado = classificador.evaluate(previsores_test, classe_test)
resultado

38/38 [==============================] - 0s 193us/step


[0.1243318531074022, 0.9736842105263158]

In [34]:
#retorna uma probabilidade para cada um dos neuronios
# acima é a função propria do keras com "evaluate", aqui é de certa forma manual
# o array de previsões, se o valor da baixo quer dizer que a saida do nueronio é 0
# Se o valor da próximo a 1, a saida do neurônio é 1, e a combinação dos três neurônios dará a classificação
previsoes = classificador.predict(previsores_test)
previsoes

array([[1.17921196e-02, 9.23721015e-01, 6.44868240e-02],
       [1.64018609e-02, 9.82139885e-01, 1.45828782e-03],
       [4.99629939e-04, 4.44937125e-02, 9.55006719e-01],
       [2.62606045e-04, 2.92570163e-02, 9.70480382e-01],
       [9.96874571e-01, 3.12539656e-03, 4.91404030e-14],
       [1.05824573e-02, 9.88622725e-01, 7.94837193e-04],
       [6.21576677e-04, 4.92000617e-02, 9.50178385e-01],
       [1.34729529e-02, 9.84733641e-01, 1.79343391e-03],
       [1.39143942e-02, 8.71439278e-01, 1.14646293e-01],
       [9.98352051e-01, 1.64800684e-03, 1.70919210e-15],
       [9.95901525e-01, 4.09841863e-03, 2.91167237e-14],
       [4.10683075e-04, 3.76944132e-02, 9.61894870e-01],
       [4.07551095e-04, 3.75089906e-02, 9.62083519e-01],
       [8.82589782e-04, 6.39800653e-02, 9.35137272e-01],
       [9.89457071e-01, 1.05429199e-02, 7.54686949e-13],
       [9.97106254e-01, 2.89373170e-03, 1.26071596e-14],
       [6.31343748e-04, 4.96944040e-02, 9.49674308e-01],
       [9.97955322e-01, 2.04465

In [37]:
previsoes_bin = (previsoes>0.5)
previsoes_bin

array([[False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [Fa

In [39]:
import numpy as np
from sklearn.metrics import confusion_matrix

In [40]:
# Para aplicar a matriz de confusão é necessario fazer algumas modificações
# Abaixo utilizamos o 'np.argmax()' que retorna o número do indice do array que contém o maior valor
# Então em ambos os casos temos arrays de 3 indices dentro de um array
# Nesses três indices o maior valor contido é do ultimo dos 3, ele retorna 2 pois o maior valor está na posição 2
# Se o maior valor estivesse na primeira posição de um dos arrays, ele retornaria 0 pois o maior valor está na posição zero.

In [41]:
classe_test2 = [np.argmax(t) for t in classe_test]
classe_test2

[1,
 1,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 2]

In [45]:
previsoes_test2 = [np.argmax(t) for t in previsoes_bin]
previsoes_test2

[1,
 1,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 2,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 2]

In [46]:
# pega os valores preditos pelo modelo os valores de teste.
# Ambos aṕos convertidos em valores unidimensionais com o "np.argmax()"

matriz = confusion_matrix(previsoes_test2, classe_test2)
matriz

array([[13,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 15]])